spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  data:
    redis:
      host: k11s103.p.ssafy.io
      port: 6379
      password: ${REDIS_PASSWORD}
    web:
      pageable:
        default-page-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # SQL 쿼리 로그 출력
  session:
    store-type: redis
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000
  redis:
    serializer: jackson2JsonRedisSerializer

server:
  servlet:
    session:
      cookie:
        path: /
        name: JSESSIONID
        http-only: true
      timeout: 3600