server:
  port: 8082
spring:
  profiles:
    active: dev
  datasource:
    hikari:
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true