spring:
  config:
    import: application-secret.yml
  data:
    redis:
      port: 6379
  datasource:
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: k11s103.p.ssafy.io:9092
#    bootstrap-servers: localhost:9092
    consumer:
      group-id: log_consumer
      auto-offset-reset: earliest
    topic:
      log-topic: pads_log_topic