spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  data:
    redis:
      host: k11s103.p.ssafy.io
      port: 6379
      password: ${REDIS_PASSWORD}
  kafka:
    bootstrap-servers: k11s103.p.ssafy.io:9092
    consumer:
      group-id: log_consumer
    topic:
      log-topic: pads_log_topic
